### ISSUE TITLE
Additional things to list

### ISSUE THREAD

**Issue by jgoerzen** [yaelwrites/Big-Ass-Data-Broker-Opt-Out-List#20]
This is another data broker:

https://optout.lexisnexis.com/

https://www.consumerreports.org/privacy/easy-opt-outs-to-protect-your-privacy-a7017744648/ has a pretty nice list.

**Comment by yaelwrites** [comment]
I haven’t included LexisNexis here because it requires substantial personal information (social security number, home address, phone number) and because it doesn’t look like suppression requests meaningfully remove personal data. It does not include third party data available through real time gateways; news; and legal documents. LexisNexis also asks for “documentation substantiating the risk of physical harm or the individual's status as an identity theft victim,” which many people don’t have. And even if you supply it, “LexisNexis reserves the right to determine, in its sole reasonable discretion, what documentation meets this criteria. If your suppression request is not approved we will promptly inform you about that determination.” The type of documentation requested includes police reports documenting identity theft, identity claims from credit card companies and identity theft affidavits, letters from supervisors stating a position (limited to law enforcement or to public officials) subjects the person to threats of death or serious bodily harm, or court protective orders, police reports, letters from shelter administrators, or health records. People are also supposed to mail their requests.

As far as the article, written by my colleague, it hasn’t been updated since 2017, and the only data broker mentioned is Acxiom, already included on the list. The Do Not Call Registry is included in the guide, as is an opt-out pre-screen site. The DMA Choice site is defunct. If you want to research newer versions of anything you think is missing, please file a pull request.
